config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts, only: [:show, :index, :create, :destroy, :new]

  get 'signup' => 'users#new'

  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :destroy]
  before_action :require_user, only: [:index, :show]

  def index
    @posts = Post.order("created_at DESC")
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def destroy
    @post.destroy
  end

  private
  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to 'login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NativeAuth</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if current_user %>
      <ul>
        <li><%= current_user.email %></li>
        <li><%= link_to "Log out", logout_path, method: "delete" %></li>
      </ul>
  <% else %>
      <ul>
        <li><%= link_to "Login", 'login' %></a></li>
        <li><%= link_to "Signup", 'signup' %></a></li>
      </ul>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.haml
- @posts.each do |post|
  %ul
    %li= link_to post.title, post
    %li= post.body

%br

= link_to 'New', new_post_path

app/views/posts/new.haml
= simple_form_for @post do |f|
  = f.input :title
  = f.input :body

  =f.submit 'Save'

%br

= link_to 'Back', posts_path

app/views/posts/show.haml
%h1= @post.title

%p= @post.body

%br

= link_to 'All Posts', posts_path

app/views/users/new.haml
%h1 Sign Up

= simple_form_for @user do |f|
 = f.input :first_name
 = f.input :last_name
 = f.input :email
 = f.input :password
 = f.submit 'Save'